version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - messaging-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - messaging-network

networks:
  messaging-network:
    driver: bridge